// apps/react/tables/libraries/AgGrid/marketing-spend-demo-single-comment/components/document/grid-components/RowNumberRenderer.tsx
import React from 'react';

export const RowNumberRenderer = (props: any) => {
  return (
    <div style={{
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
      height: '100%',
      fontFamily: 'DM Mono, monospace',
      fontSize: '12px',
      color: 'rgba(255, 255, 255, 0.5)',
      letterSpacing: '0.12px'
    }}>
      {props.node.rowIndex + 2}
    </div>
  );
};

// apps/vue/comments/tables/ag-grid/multiple-tools/src/components/document/grid-components/RowNumberRenderer.vue
<template>
  <div :style="{
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    fontFamily: 'DM Mono, monospace',
    fontSize: '12px',
    color: 'rgba(255, 255, 255, 0.5)',
    letterSpacing: '0.12px',
  }">
    {{ params.node.rowIndex + 1 }}
  </div>
</template>

<script setup lang="ts">
defineProps<{ params: any }>();
</script>
