// apps/react/tables/libraries/ag-grid/single-tool/components/document/grid-components/VeltCellRenderer.tsx
import React from 'react';
import { CellFormatting } from '../types';
import { getCellFormattingKey } from '../utils';

export const createVeltCellRenderer = (
  cellFormatting: Record<string, CellFormatting>,
  documentId: string | null
) => {
  const VeltCellRenderer = (props: any) => {
  const cellId = `cell-${props.data.id}-${props.colDef.field}`;
  const cellKey = getCellFormattingKey(props.data.id, props.colDef.field);
  const formatting = cellFormatting[cellKey] || {};

  // [Velt] Set ID and attributes on parent AG Grid cell element
  React.useEffect(() => {
    if (props.eGridCell) {
      // [Velt] Set the element ID
      props.eGridCell.id = cellId;
      // [Velt] For single-tool pattern: add data-velt-target-comment-element-id
      // This allows the single comment tool to attach comments to this specific cell
      // Both id and data-velt-target-comment-element-id must have the same value
      props.eGridCell.setAttribute('data-velt-target-comment-element-id', cellId);
    }
  }, [cellId, props.eGridCell]);

  const textStyle: React.CSSProperties = {
    fontWeight: formatting.bold ? 'bold' : 'normal',
    fontStyle: formatting.italic ? 'italic' : 'normal',
    textDecoration: [
      formatting.underline ? 'underline' : '',
      formatting.strikethrough ? 'line-through' : '',
    ].filter(Boolean).join(' ') || 'none',
  };

  const containerStyle: React.CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '100%',
    height: '100%',
    padding: '4px 12px 4px 12px',
    textAlign: formatting.align || 'left',
  };

  return (
    <div style={containerStyle}>
      <span style={textStyle}>{props.value}</span>
    </div>
  );
  };

  VeltCellRenderer.displayName = 'VeltCellRenderer';
  return VeltCellRenderer;
};

// apps/vue/comments/tables/ag-grid/multiple-tools/src/components/document/grid-components/VeltCellRenderer.vue
<template>
  <div
    ref="cellRef"
    :style="{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%', height: '100%' }"
  >
    <span :style="{ ...textStyle, paddingLeft: '12px' }">{{ params.value }}</span>
    <div :style="{ display: 'flex', alignItems: 'center', gap: '4px', paddingRight: '8px' }">
      <!-- [Velt] velt-comment-tool renders a button that allows users to add comments to this specific cell -->
      <!-- [Velt] target-element-id references the parent AG Grid cell with the ID set above -->
      <!-- [Velt] Comment tool only appears on hover over the entire cell -->
      <velt-comment-tool
        v-if="isHovered"
        :target-element-id="cellId"
      ></velt-comment-tool>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import type { CellFormatting } from '../types';
import { getCellFormattingKey } from '../utils';

const props = defineProps<{ params: any }>();

const cellRef = ref<HTMLDivElement | null>(null);
const isHovered = ref(false);

const cellId = computed(() => `cell-${props.params.data.id}-${props.params.colDef.field}`);
const cellKey = computed(() => getCellFormattingKey(props.params.data.id, props.params.colDef.field));

const formatting = computed<CellFormatting>(() => {
  const cf = props.params.cellFormatting || {};
  return cf[cellKey.value] || {};
});

const textStyle = computed(() => ({
  fontWeight: formatting.value.bold ? 'bold' : 'normal',
  fontStyle: formatting.value.italic ? 'italic' : 'normal',
  textDecoration: [
    formatting.value.underline ? 'underline' : '',
    formatting.value.strikethrough ? 'line-through' : '',
  ].filter(Boolean).join(' ') || 'none',
}));

let parentCell: Element | null = null;
const handleMouseEnter = () => { isHovered.value = true; };
const handleMouseLeave = () => { isHovered.value = false; };

// [Velt] Set ID on parent AG Grid cell element and add hover listeners to the cell
onMounted(() => {
  requestAnimationFrame(() => {
    if (!cellRef.value) return;
    parentCell = cellRef.value.closest('.ag-cell');
    if (parentCell) {
      if (parentCell.id !== cellId.value) {
        parentCell.id = cellId.value;
      }
      parentCell.addEventListener('mouseenter', handleMouseEnter);
      parentCell.addEventListener('mouseleave', handleMouseLeave);
    }
  });
});

onUnmounted(() => {
  if (parentCell) {
    parentCell.removeEventListener('mouseenter', handleMouseEnter);
    parentCell.removeEventListener('mouseleave', handleMouseLeave);
  }
});
</script>
