// apps/vue/comments/tables/ag-grid/multiple-tools/src/components/document/DayViewTableComponent.vue
<template>
  <div :style="styles.container">
    <Breadcrumb />

    <div :style="styles.tableContainer">
      <ViewToggle />

      <Toolbar @toggle-formatting="toggleFormatting" />

      <div :style="styles.gridWrapper">
        <ag-grid-vue
          :theme="agGridTheme"
          :rowData="rowData"
          :columnDefs="columnDefs"
          :defaultColDef="defaultColDef"
          :domLayout="'normal'"
          :enableCellTextSelection="true"
          :ensureDomOrder="true"
          :animateRows="false"
          :suppressRowHoverHighlight="false"
          :suppressAnimationFrame="false"
          :suppressCellFocus="false"
          :getRowId="getRowId"
          @grid-ready="onGridReady"
          @sort-changed="onSortChanged"
          @cell-clicked="onCellClicked"
          @cell-value-changed="onCellValueChanged"
          style="width: 100%; height: 100%"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, watch, markRaw } from 'vue';
import { AgGridVue } from 'ag-grid-vue3';
import { AllCommunityModule, ModuleRegistry } from 'ag-grid-community';
import './day-view-table-component.css';

import { customDarkTheme, customLightTheme } from './constants';
import { useTheme } from '@/composables/useTheme';
import { dateComparator } from './utils';
import CustomHeaderComponent from './grid-components/CustomHeaderComponent.vue';
import RowNumberRenderer from './grid-components/RowNumberRenderer.vue';
import RowNumberHeaderComponent from './grid-components/RowNumberHeaderComponent.vue';
import VeltCellRenderer from './grid-components/VeltCellRenderer.vue';
import Breadcrumb from './ui-components/Breadcrumb.vue';
import ViewToggle from './ui-components/ViewToggle.vue';
import Toolbar from './ui-components/Toolbar.vue';
import { styles } from './styles';
import { useTableState } from '@/composables/useTableState';

// Register AG Grid modules
ModuleRegistry.registerModules([AllCommunityModule]);

const { resolvedTheme } = useTheme();
const agGridTheme = computed(() => resolvedTheme.value === 'dark' ? customDarkTheme : customLightTheme);

const {
  selectedCell,
  rowData,
  cellFormatting,
  gridApi,
  sortState,
  localSortState,
  toggleFormatting,
} = useTableState();

// Sync localSortState with sortState
watch(sortState, (newVal) => {
  if (newVal) {
    localSortState.value = newVal;
  }
});

// Update header highlighting when selection changes
watch(selectedCell, (newSelectedCell) => {
  if (gridApi.value) {
    document.querySelectorAll('.ag-header-cell').forEach(el => {
      el.classList.remove('header-selected');
    });
    document.querySelectorAll('.ag-pinned-left-cols-container .ag-cell').forEach(el => {
      el.classList.remove('row-selected');
    });

    if (newSelectedCell) {
      const colElement = document.querySelector(`[col-id="${newSelectedCell.col}"]`);
      if (colElement) {
        colElement.classList.add('header-selected');
      }

      const allCells = document.querySelectorAll('.ag-pinned-left-cols-container .ag-cell');
      allCells.forEach(cell => {
        const row = cell.closest('.ag-row');
        if (row) {
          const rowNode = gridApi.value.getRowNode(newSelectedCell.row.toString());
          if (rowNode && row.getAttribute('row-id') === newSelectedCell.row.toString()) {
            cell.classList.add('row-selected');
          }
        }
      });
    }
  }
});

function setLocalSort(state: any) {
  localSortState.value = state;
}

const columnDefs = computed(() => [
  {
    headerName: '',
    field: 'rowNumber' as any,
    width: 50,
    pinned: 'left' as const,
    lockPosition: true,
    suppressHeaderMenuButton: true,
    sortable: false,
    editable: false,
    cellRenderer: markRaw(RowNumberRenderer),
    headerComponent: markRaw(RowNumberHeaderComponent),
    cellStyle: {
      backgroundColor: 'var(--app-surface)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  {
    field: 'date' as any,
    headerName: 'Dates',
    headerComponent: markRaw(CustomHeaderComponent),
    headerComponentParams: {
      localSortState: localSortState.value,
      setLocalSortState: setLocalSort,
    },
    editable: true,
    sortable: true,
    comparator: dateComparator,
    cellRenderer: markRaw(VeltCellRenderer),
    cellRendererParams: {
      cellFormatting: cellFormatting.value,
    },
    flex: 1,
    minWidth: 150,
  },
  {
    field: 'x' as any,
    headerName: 'X',
    headerComponent: markRaw(CustomHeaderComponent),
    headerComponentParams: {
      localSortState: localSortState.value,
      setLocalSortState: setLocalSort,
    },
    editable: true,
    sortable: true,
    cellRenderer: markRaw(VeltCellRenderer),
    cellRendererParams: {
      cellFormatting: cellFormatting.value,
    },
    flex: 1,
    minWidth: 120,
  },
  {
    field: 'linkedin' as any,
    headerName: 'LinkedIn',
    headerComponent: markRaw(CustomHeaderComponent),
    headerComponentParams: {
      localSortState: localSortState.value,
      setLocalSortState: setLocalSort,
    },
    editable: true,
    sortable: true,
    cellRenderer: markRaw(VeltCellRenderer),
    cellRendererParams: {
      cellFormatting: cellFormatting.value,
    },
    flex: 1,
    minWidth: 120,
  },
  {
    field: 'facebook' as any,
    headerName: 'Facebook',
    headerComponent: markRaw(CustomHeaderComponent),
    headerComponentParams: {
      localSortState: localSortState.value,
      setLocalSortState: setLocalSort,
    },
    editable: true,
    sortable: true,
    cellRenderer: markRaw(VeltCellRenderer),
    cellRendererParams: {
      cellFormatting: cellFormatting.value,
    },
    flex: 1,
    minWidth: 120,
  },
  {
    field: 'instagram' as any,
    headerName: 'Instagram',
    headerComponent: markRaw(CustomHeaderComponent),
    headerComponentParams: {
      localSortState: localSortState.value,
      setLocalSortState: setLocalSort,
    },
    editable: true,
    sortable: true,
    cellRenderer: markRaw(VeltCellRenderer),
    cellRendererParams: {
      cellFormatting: cellFormatting.value,
    },
    flex: 1,
    minWidth: 120,
  },
]);

const defaultColDef = {
  resizable: true,
  sortable: true,
  editable: true,
};

function getRowId(params: any) {
  return params.data.id.toString();
}

function onGridReady(params: any) {
  gridApi.value = params.api;
  params.api.applyColumnState({
    state: [{ colId: 'date', sort: 'asc' }],
    defaultState: { sort: null },
  });
  sortState.value = { colId: 'date', sort: 'asc' };
  localSortState.value = { colId: 'date', sort: 'asc' };
}

function onSortChanged(params: any) {
  const columnState = params.api.getColumnState();
  const sortedColumn = columnState.find((col: any) => col.sort !== null);
  sortState.value = sortedColumn ? { colId: sortedColumn.colId, sort: sortedColumn.sort } : null;
}

function onCellClicked(params: any) {
  if (params.data) {
    selectedCell.value = {
      row: params.data.id,
      col: params.colDef.field,
    };
  }
}

function onCellValueChanged(params: any) {
  const idx = rowData.value.findIndex(row => row.id === params.data.id);
  if (idx !== -1) {
    rowData.value[idx] = { ...params.data };
  }
}
</script>

// apps/react/comments/tables/ag-grid/multiple-tools/components/document/day-view-table-component.tsx
'use client';

import React, { useEffect, useMemo, useCallback } from 'react';
import { AgGridReact } from 'ag-grid-react';
import { AllCommunityModule, ModuleRegistry } from 'ag-grid-community';
import './day-view-table-component.css';

// Register AG Grid modules
ModuleRegistry.registerModules([AllCommunityModule]);

// Import modularized components and utilities
import { customDarkTheme, customLightTheme } from './constants';
import { useTheme } from '@/components/theme/ThemeContext';
import { dateComparator } from './utils';
import { createCustomHeaderComponent } from './grid-components/CustomHeaderComponent';
import { RowNumberRenderer } from './grid-components/RowNumberRenderer';
import { createVeltCellRenderer } from './grid-components/VeltCellRenderer';
import { Breadcrumb } from './ui-components/Breadcrumb';
import { ViewToggle } from './ui-components/ViewToggle';
import { Toolbar } from './ui-components/Toolbar';
import { styles } from './styles';
import { useTableState } from './hooks/useTableState';

export const TableComponent: React.FC = () => {
  const {
    selectedCell,
    setSelectedCell,
    rowData,
    setRowData,
    cellFormatting,
    gridApi,
    setGridApi,
    sortState,
    setSortState,
    localSortState,
    setLocalSortState,
    toggleFormatting,
  } = useTableState();

  const { resolvedTheme } = useTheme();
  const gridTheme = resolvedTheme === 'dark' ? customDarkTheme : customLightTheme;

  // Sync localSortState with sortState (when AG Grid updates)
  useEffect(() => {
    if (sortState) {
      setLocalSortState(sortState);
    }
  }, [sortState]);

  // Update header highlighting when selection changes
  useEffect(() => {
    if (gridApi) {
      // Remove all previous highlighting
      document.querySelectorAll('.ag-header-cell').forEach(el => {
        el.classList.remove('header-selected');
      });
      document.querySelectorAll('.ag-pinned-left-cols-container .ag-cell').forEach(el => {
        el.classList.remove('row-selected');
      });

      if (selectedCell) {
        // Add highlighting to selected column header
        const colElement = document.querySelector(`[col-id="${selectedCell.col}"]`);
        if (colElement) {
          colElement.classList.add('header-selected');
        }

        // Add highlighting to selected row number
        const allCells = document.querySelectorAll('.ag-pinned-left-cols-container .ag-cell');
        allCells.forEach(cell => {
          const row = cell.closest('.ag-row');
          if (row) {
            const rowNode = gridApi.getRowNode(selectedCell.row.toString());
            if (rowNode && row.getAttribute('row-id') === selectedCell.row.toString()) {
              cell.classList.add('row-selected');
            }
          }
        });
      }
    }
  }, [selectedCell, gridApi]);

  // Create header component with sorting
  const headerComponent = useMemo(() => {
    return createCustomHeaderComponent(localSortState, setLocalSortState);
  }, [localSortState]);

  // [Velt] Cell Renderer with Velt formatting
  const veltCellRenderer = useMemo(() => {
    return createVeltCellRenderer(cellFormatting);
  }, [cellFormatting]);

  // Column Definitions
  const columnDefs = useMemo(() => [
    {
      headerName: '',
      field: 'rowNumber' as any,
      width: 50,
      pinned: 'left' as const,
      lockPosition: true,
      suppressHeaderMenuButton: true,
      sortable: false,
      editable: false,
      cellRenderer: RowNumberRenderer,
      headerComponent: () => (
        <div style={{
          fontFamily: 'DM Mono, monospace',
          fontSize: '14px',
          opacity: 0,
        }}>
          -
        </div>
      ),
      cellStyle: {
        backgroundColor: 'var(--app-surface)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
      } as any,
    },
    {
      field: 'date' as any,
      headerName: 'Dates',
      headerComponent: headerComponent,
      editable: true,
      sortable: true,
      comparator: dateComparator,
      cellRenderer: veltCellRenderer,
      flex: 1,
      minWidth: 150,
    },
    {
      field: 'x' as any,
      headerName: 'X',
      headerComponent: headerComponent,
      editable: true,
      sortable: true,
      cellRenderer: veltCellRenderer,
      flex: 1,
      minWidth: 120,
    },
    {
      field: 'linkedin' as any,
      headerName: 'LinkedIn',
      headerComponent: headerComponent,
      editable: true,
      sortable: true,
      cellRenderer: veltCellRenderer,
      flex: 1,
      minWidth: 120,
    },
    {
      field: 'facebook' as any,
      headerName: 'Facebook',
      headerComponent: headerComponent,
      editable: true,
      sortable: true,
      cellRenderer: veltCellRenderer,
      flex: 1,
      minWidth: 120,
    },
    {
      field: 'instagram' as any,
      headerName: 'Instagram',
      headerComponent: headerComponent,
      editable: true,
      sortable: true,
      cellRenderer: veltCellRenderer,
      flex: 1,
      minWidth: 120,
    },
  ], [veltCellRenderer, headerComponent]);

  // Default column properties
  const defaultColDef = useMemo(() => ({
    resizable: true,
    sortable: true,
    editable: true,
  }), []);

  // AG Grid event handlers
  const onGridReady = useCallback((params: any) => {
    setGridApi(params.api);
    params.api.applyColumnState({
      state: [{ colId: 'date', sort: 'asc' }],
      defaultState: { sort: null },
    });
    setSortState({ colId: 'date', sort: 'asc' });
    setLocalSortState({ colId: 'date', sort: 'asc' });
  }, []);

  const onSortChanged = useCallback((params: any) => {
    const columnState = params.api.getColumnState();
    const sortedColumn = columnState.find((col: any) => col.sort !== null);
    setSortState(sortedColumn ? { colId: sortedColumn.colId, sort: sortedColumn.sort } : null);
  }, []);

  const onCellClicked = useCallback((params: any) => {
    if (params.data) {
      setSelectedCell({
        row: params.data.id,
        col: params.colDef.field,
      });
    }
  }, []);

  const onCellValueChanged = useCallback((params: any) => {
    setRowData(prevData => {
      const updatedData = [...prevData];
      const rowIndex = updatedData.findIndex(row => row.id === params.data.id);
      if (rowIndex !== -1) {
        updatedData[rowIndex] = { ...params.data };
      }
      return updatedData;
    });
  }, []);

  return (
    <div style={styles.container}>
      <Breadcrumb />

      <div style={styles.tableContainer}>
        <ViewToggle />

        <Toolbar
          toggleFormatting={toggleFormatting}
        />

        <div style={styles.gridWrapper}>
          <AgGridReact
            theme={gridTheme}
            rowData={rowData}
            columnDefs={columnDefs}
            defaultColDef={defaultColDef}
            onGridReady={onGridReady}
            onSortChanged={onSortChanged}
            onCellClicked={onCellClicked}
            onCellValueChanged={onCellValueChanged}
            domLayout="normal"
            enableCellTextSelection={true}
            ensureDomOrder={true}
            animateRows={false}
            suppressRowHoverHighlight={false}
            suppressAnimationFrame={false}
            suppressCellFocus={false}
            getRowId={(params) => params.data.id.toString()}
          />
        </div>
      </div>
    </div>
  );
};

export default TableComponent;
