// apps/react/comments/text-editors/codemirror/codemirror-demo/components/document/document-canvas.tsx
'use client'

import Header from '@/components/header/header'
import Sidebar from '@/components/sidebar/sidebar'
import CodeEditorTabs from '@/components/document/CodeMirror Components/CodeEditorTabs'
import { VeltCollaboration } from '@/components/velt/VeltCollaboration'

export default function DocumentCanvas() {
  return (
    <div className="flex flex-col w-full h-full">
      <VeltCollaboration />
      <Header />
      <div className="flex flex-1 overflow-hidden">
        <Sidebar />
        <div className="flex-1 p-4">
          <div className="w-full h-full border rounded-lg bg-card p-4">
            <div className="h-full flex flex-col">
              <CodeEditorTabs />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// apps/vue/comments/tables/ag-grid/multiple-tools/src/components/document/DocumentCanvas.vue
<template>
  <div class="flex w-full h-screen overflow-hidden bg-black">
    <Sidebar />
    <div class="flex-1 overflow-auto relative">
      <Header />
      <DayViewTableComponent />
    </div>
  </div>
</template>

<script setup lang="ts">
import Header from '@/components/header/Header.vue';
import Sidebar from '@/components/sidebar/Sidebar.vue';
import DayViewTableComponent from './DayViewTableComponent.vue';
import { provideSidebar } from '@/composables/useSidebar';

provideSidebar();
</script>
