// apps/react/tables/libraries/ag-grid/multiple-tools/components/velt/VeltCollaboration.tsx
"use client";
import { useVeltClient, VeltComments, VeltCommentsSidebar } from "@veltdev/react";
import VeltInitializeDocument from "./VeltInitializeDocument";
import { VeltCustomization } from "./ui-customization/VeltCustomization";
import { useEffect } from "react";
import { useAppUser } from "@/app/userAuth/AppUserContext";

export function VeltCollaboration() {
  const { isUserLoggedIn } = useAppUser();
  const { client } = useVeltClient();

  // [Velt] Sign out user when user logs out, getting user login state from host app
  useEffect(() => {
    if (isUserLoggedIn === false && client) {
      client.signOutUser();
    }
  }, [isUserLoggedIn, client]);

  // [Velt] Enable dark mode
  useEffect(() => {
    if (client) {
      client.setDarkMode(true);
    }
  }, [client]);

  // [Velt] Disable comment pin highlighter
  useEffect(() => {
    if (client) {
      client.getCommentElement().disableCommentPinHighlighter();
    }
  }, [client]);

  const groupConfig = {
    enable: false
  };

  return (
    <>
      <VeltInitializeDocument />
      <VeltComments
        popoverTriangleComponent={true}
        popoverMode={true}
        shadowDom={false}
        textMode={false}
        commentPinHighlighter={false}
        dialogOnHover={false}
      />
      <VeltCommentsSidebar groupConfig={groupConfig} />
      <VeltCustomization />
    </>
  );
}

// apps/vue/comments/tables/ag-grid/multiple-tools/src/components/velt/VeltCollaboration.vue
<template>
  <VeltInitializeDocument />
  <!-- [Velt] Comments with popover mode -->
  <velt-comments
    popover-mode="true"
    shadow-dom="false"
    text-mode="false"
    comment-pin-highlighter="false"
    dialog-on-hover="false"
  ></velt-comments>
  <!-- [Velt] Comments sidebar -->
  <velt-comments-sidebar group-config='{"enable": false}'></velt-comments-sidebar>
  <VeltCustomization />
</template>

<script setup lang="ts">
import { watch } from 'vue';
import { useVeltClient } from '@/composables/useVeltClient';
import { useAppUser } from '@/composables/useAppUser';
import VeltInitializeDocument from './VeltInitializeDocument.vue';
import VeltCustomization from './ui-customization/VeltCustomization.vue';

const { client } = useVeltClient();
const { isUserLoggedIn } = useAppUser();

// [Velt] Sign out user when user logs out
watch(
  [isUserLoggedIn, client],
  ([loggedIn, veltClient]) => {
    if (loggedIn === false && veltClient) {
      veltClient.signOutUser();
    }
  }
);
</script>
