// apps/react/tables/libraries/tanstack/multiple-tools/components/velt/VeltTools.tsx
"use client";
import {
  VeltPresence,
  VeltSidebarButton,
  VeltNotificationsTool,
  VeltCommentTool,
} from "@veltdev/react";

function VeltTools() {
  return (
    <>
      // [Velt] Show online users
      <VeltPresence />
      // [Velt] Toggle comments sidebar
      <VeltSidebarButton />
      // [Velt] Add comment tool
      <VeltCommentTool />
      // [Velt] Notifications panel
      <VeltNotificationsTool
        settings={true}
        shadowDom={false}
        tabConfig={{
          forYou: { name: "For You", enable: true },
          documents: { name: "Documents", enable: true },
          all: { name: "All", enable: true },
        }}
      />
    </>
  );
}

export default VeltTools;

// apps/vue/comments/tables/ag-grid/multiple-tools/src/components/velt/VeltTools.vue
<template>
  <template v-if="client">
    <!-- [Velt] Show online users -->
    <velt-presence></velt-presence>
    <!-- [Velt] Toggle comments sidebar -->
    <velt-sidebar-button></velt-sidebar-button>
    <!-- [Velt] Notifications panel -->
    <velt-notifications-tool
      settings="true"
      shadow-dom="false"
      tab-config='{"forYou":{"name":"For You","enable":true},"documents":{"name":"Documents","enable":true},"all":{"name":"All","enable":true}}'
    ></velt-notifications-tool>
  </template>
</template>

<script setup lang="ts">
import { useVeltClient } from '@/composables/useVeltClient';

const { client } = useVeltClient();
</script>
