// apps/react/comments/spreadsheets/spreadjs/spreadjs-comments-demo/components/sidebar/sidebar.tsx
'use client'

import { useState } from 'react'
import { SHEET_NAV_ITEMS } from '../document/SpreadJSComponent/constants'

const imgTablerIconChevronLeftPipe = "/icons/chevron-left-pipe.svg"

interface TableOfContentsItem {
  id: string
  label: string
  sheetName: string
}

const tableOfContentsItems: TableOfContentsItem[] = SHEET_NAV_ITEMS.map((item) => ({ ...item }))

interface SidebarProps {
  onActivateSheet?: (sheetName: string) => void
}

export default function Sidebar({ onActivateSheet }: SidebarProps) {
  const [activeItem, setActiveItem] = useState('sheet-sales')
  const [isCollapsed, setIsCollapsed] = useState(true)

  return (
    <>
      {/* Expand Button - shown when sidebar is collapsed */}
      {isCollapsed && (
        <div
          className="fixed left-4 top-4 z-50 cursor-pointer flex items-center justify-center"
          onClick={() => setIsCollapsed(false)}
          style={{
            width: "40px",
            height: "40px",
            backgroundColor: "var(--app-sidebar-bg)",
            borderRadius: "8px",
          }}
        >
          <img
            src={imgTablerIconChevronLeftPipe}
            alt="Expand"
            className="block max-w-none w-5 h-5"
            style={{ transform: 'rotate(180deg)', filter: 'var(--app-icon-invert)' }}
          />
        </div>
      )}

      {/* Sidebar - with smooth animation */}
      <aside
        className="relative transition-all duration-300"
        style={{
          color: 'var(--app-text-primary)',
          width: isCollapsed ? "0px" : "254px",
          height: "calc(100vh - 32px)",
          backgroundColor: 'var(--app-sidebar-bg)',
          borderRadius: '12px',
          boxShadow: '0px -24px 100px 0px rgba(0, 0, 0, 0.25)',
          margin: "16px",
          marginRight: "8px",
          overflow: "hidden",
          opacity: isCollapsed ? 0 : 1,
        }}
      >
      <div className="absolute left-[24px] top-[24px] right-[55px] flex flex-col gap-[8px]">
        <div className="flex items-start gap-[6px]">
          <div className="relative shrink-0 size-[12px] opacity-50">
            <svg width="12" height="12" viewBox="0 0 8 6" fill="none" xmlns="http://www.w3.org/2000/svg">
              <rect x="0" y="0" width="8" height="1" fill="currentColor" />
              <rect x="0" y="2.5" width="8" height="1" fill="currentColor" />
              <rect x="0" y="5" width="8" height="1" fill="currentColor" />
            </svg>
          </div>
          <p className="font-['Urbanist',sans-serif] font-normal leading-none opacity-50 text-[12px] text-current whitespace-pre">
            Mihir&apos;s Workspace
          </p>
        </div>

        <p className="font-['Urbanist',sans-serif] font-semibold leading-none opacity-90 text-[16px] text-current whitespace-pre">
          SpreadJS Workbook
        </p>
      </div>

      <div className="absolute left-[24px] top-[155px] right-[24px] bottom-[384px] flex flex-col gap-[12px]">
        <div className="flex gap-[8px] items-center justify-between">
          <div className="font-['Geist_Mono',monospace] font-normal leading-[0] opacity-[0.52] text-[10px] text-current uppercase">
            <p className="leading-[1.5] whitespace-pre">Table of Contents</p>
          </div>
          <button
            onClick={() => setIsCollapsed(true)}
            className="flex gap-2.5 items-center p-2 rounded-full shrink-0 transition-colors -mr-2"
            style={{ filter: 'var(--app-icon-invert)' }}
          >
            <img
              src={imgTablerIconChevronLeftPipe}
              alt="Collapse"
              className="block max-w-none w-5 h-5"
            />
          </button>
        </div>

        <div className="flex flex-col">
          {tableOfContentsItems.map((item, index) => {
            const isActive = activeItem === item.id
            return (
              <button
                key={item.id}
                onClick={() => {
                  setActiveItem(item.id)
                  if (onActivateSheet) {
                    onActivateSheet(item.sheetName)
                  }
                }}
                className={`flex gap-[${isActive ? '8' : '10'}px] items-center ${isActive ? '' : 'opacity-[0.52]'} w-full text-left`}
              >
                <div className="flex flex-row items-center self-stretch">
                  <div className="h-full overflow-clip relative shrink-0 w-[12px]">
                    <div className="absolute bottom-0 left-1/2 top-0 -translate-x-1/2 w-px" style={{ backgroundColor: 'var(--app-text-muted)' }} />
                    {isActive && (
                      <div className="absolute bg-[#ffc31c] bottom-[7px] left-1/2 top-[7px] -translate-x-1/2 w-[2px]" />
                    )}
                  </div>
                </div>

                <div className="font-['Geist_Mono',monospace] font-normal text-[12px] text-current">
                  <p className="leading-[2.2] whitespace-pre">{item.label}</p>
                </div>
              </button>
            )
          })}
        </div>
      </div>

    </aside>
    </>
  )
}

// apps/vue/comments/tables/ag-grid/multiple-tools/src/components/sidebar/Sidebar.vue
<template>
  <!-- Expand Button - shown when sidebar is collapsed -->
  <div
    v-if="isCollapsed"
    class="fixed left-4 top-4 z-50 cursor-pointer flex items-center justify-center"
    @click="toggleSidebar"
    :style="{
      width: '40px',
      height: '40px',
      backgroundColor: 'var(--app-sidebar-bg)',
      borderRadius: '8px',
    }"
  >
    <IconChevronRightPipe :size="20" :style="{ color: 'var(--app-text-primary)' }" stroke="1" />
  </div>

  <aside
    class="flex flex-col justify-between transition-all duration-300"
    :style="{
      width: isCollapsed ? '0px' : '251px',
      height: 'calc(100vh - 32px)',
      backgroundColor: 'var(--app-sidebar-bg)',
      borderRadius: '12px',
      margin: '16px',
      marginRight: '8px',
      overflow: 'hidden',
      opacity: isCollapsed ? 0 : 1,
    }"
  >
    <!-- Top Section -->
    <div class="flex flex-col">
      <!-- Header -->
      <div
        class="flex flex-row justify-between items-center"
        :style="{
          paddingTop: '12px',
          paddingRight: '12px',
          paddingBottom: '12px',
          paddingLeft: '16px',
          gap: '45px',
          height: '48px',
        }"
      >
        <div class="flex flex-row items-center" :style="{ gap: '8px' }">
          <IconMenu2 :size="16" :style="{ color: 'var(--app-text-primary)' }" stroke="1" />
          <span :style="{
            color: 'var(--app-text-primary)',
            fontFamily: 'Urbanist, sans-serif',
            fontSize: '14px',
            fontWeight: 400,
            lineHeight: '14px',
          }">Bingo's Workspace</span>
        </div>

        <div
          class="flex flex-row items-center cursor-pointer"
          @click="toggleSidebar"
          :style="{
            padding: '4px',
            width: '24px',
            height: '24px',
            gap: '10px',
          }"
        >
          <IconChevronLeftPipe :size="16" :style="{ color: 'var(--app-text-primary)' }" stroke="1" />
        </div>
      </div>

      <!-- Navigation Section -->
      <div
        class="flex flex-col items-start flex-1 overflow-auto"
        :style="{ padding: '8px', gap: '16px' }"
      >
        <div class="flex flex-col items-start" :style="{ width: '235px', gap: '4px' }">
          <!-- Starred Label -->
          <div
            class="flex flex-row items-start"
            :style="{
              borderRadius: '32px',
              padding: '6px 8px',
              gap: '4px',
              height: '24px',
            }"
          >
            <span :style="{
              color: 'var(--app-sidebar-text-muted)',
              fontFamily: 'Urbanist, sans-serif',
              fontSize: '12px',
              fontWeight: 600,
              lineHeight: '12px',
            }">Starred</span>
          </div>

          <!-- FY2023 -->
          <div class="flex flex-col items-start" :style="{ gap: '2px' }">
            <div
              class="flex flex-row items-center cursor-pointer"
              @click="toggleSection('FY2023')"
              :style="{
                borderRadius: '8px',
                padding: '8px',
                gap: '12px',
                width: '235px',
                height: '32px',
              }"
            >
              <IconFolder :size="14" :style="{ color: 'var(--app-text-primary)' }" stroke="1" />
              <span :style="navLabelStyle">FY2023</span>
            </div>
          </div>

          <!-- FY2024 -->
          <div class="flex flex-col items-start" :style="{ gap: '2px' }">
            <div
              class="flex flex-row items-center cursor-pointer"
              @click="toggleSection('FY2024')"
              :style="{
                borderRadius: '8px',
                padding: '8px',
                gap: '12px',
                width: '235px',
                height: '32px',
              }"
            >
              <IconFolder :size="14" :style="{ color: 'var(--app-text-primary)' }" stroke="1" />
              <span :style="navLabelStyle">FY2024</span>
            </div>

            <!-- FY2024 Nested Items -->
            <div
              v-if="expandedSections.FY2024"
              class="flex flex-col items-start justify-center"
              :style="{
                borderRadius: '8px',
                gap: '4px',
                padding: '8px 0 8px 24px',
                width: '235px',
              }"
            >
              <div class="flex flex-row items-center" :style="nestedItemStyle">
                <IconSpeakerphone :size="16" :style="{ color: 'var(--app-text-primary)' }" stroke="1" />
                <span :style="nestedLabelStyle">Marketing Spend</span>
              </div>
              <div class="flex flex-row items-center" :style="nestedItemStyle">
                <IconCurrencyDollar :size="16" :style="{ color: 'var(--app-text-primary)' }" stroke="1" />
                <span :style="nestedLabelStyle">Salaries</span>
              </div>
              <div class="flex flex-row items-center" :style="nestedItemStyle">
                <IconFileAnalytics :size="16" :style="{ color: 'var(--app-text-primary)' }" stroke="1" />
                <span :style="nestedLabelStyle">Misc.</span>
              </div>
            </div>
          </div>

          <!-- FY2025 -->
          <div class="flex flex-col items-start" :style="{ gap: '2px' }">
            <div
              class="flex flex-row items-center cursor-pointer"
              @click="toggleSection('FY2025')"
              :style="{
                borderRadius: '8px',
                padding: '8px',
                gap: '12px',
                width: '235px',
                height: '32px',
              }"
            >
              <IconFolder :size="14" :style="{ color: 'var(--app-text-primary)' }" stroke="1" />
              <span :style="navLabelStyle">FY2025</span>
            </div>

            <!-- FY2025 Nested Items -->
            <div
              v-if="expandedSections.FY2025"
              class="flex flex-col items-start justify-center"
              :style="{
                borderRadius: '8px',
                gap: '4px',
                padding: '8px 0 8px 24px',
                width: '235px',
              }"
            >
              <!-- Marketing Spend - Selected State -->
              <div
                class="flex flex-row items-center"
                :style="{
                  backgroundColor: 'var(--app-sidebar-selected)',
                  borderRadius: '8px',
                  padding: '8px',
                  gap: '12px',
                  width: '211px',
                  height: '32px',
                }"
              >
                <IconSpeakerphone :size="16" color="rgb(255, 205, 46)" stroke="1" />
                <span :style="nestedLabelStyle">Marketing Spend</span>
              </div>
              <div class="flex flex-row items-center" :style="nestedItemStyle">
                <IconCurrencyDollar :size="16" :style="{ color: 'var(--app-text-primary)' }" stroke="1" />
                <span :style="nestedLabelStyle">Salaries</span>
              </div>
              <div class="flex flex-row items-center" :style="nestedItemStyle">
                <IconFileAnalytics :size="16" :style="{ color: 'var(--app-text-primary)' }" stroke="1" />
                <span :style="nestedLabelStyle">Misc.</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Bottom Section - Settings -->
    <div
      class="flex flex-row items-center"
      :style="{ padding: '16px', gap: '8px' }"
    >
      <IconSettings :size="16" :style="{ color: 'var(--app-text-primary)' }" stroke="1" />
      <span :style="{
        color: 'var(--app-text-primary)',
        fontFamily: 'Urbanist, sans-serif',
        fontSize: '14px',
        fontWeight: 400,
        lineHeight: '17px',
      }">Settings</span>
    </div>
  </aside>
</template>

<script setup lang="ts">
import { reactive } from 'vue';
import {
  IconMenu2,
  IconChevronLeftPipe,
  IconChevronRightPipe,
  IconFolder,
  IconSpeakerphone,
  IconCurrencyDollar,
  IconFileAnalytics,
  IconSettings,
} from '@tabler/icons-vue';
import { useSidebar } from '@/composables/useSidebar';

const { isCollapsed, toggleSidebar } = useSidebar();

const expandedSections = reactive<Record<string, boolean>>({
  FY2023: false,
  FY2024: true,
  FY2025: true,
});

function toggleSection(section: string) {
  expandedSections[section] = !expandedSections[section];
}

const navLabelStyle = {
  color: 'var(--app-text-primary)',
  fontFamily: 'Urbanist, sans-serif',
  fontSize: '15px',
  fontWeight: 400,
  lineHeight: '15px',
  width: '193px',
};

const nestedItemStyle = {
  borderRadius: '8px',
  padding: '8px',
  gap: '12px',
  width: '211px',
  height: '32px',
};

const nestedLabelStyle = {
  color: 'var(--app-text-primary)',
  fontFamily: 'Urbanist, sans-serif',
  fontSize: '15px',
  fontWeight: 400,
  lineHeight: '15px',
  width: '167px',
};
</script>
