// apps/vue/comments/tables/ag-grid/multiple-tools/src/App.vue
<template>
  <VeltInitializeUser />
  <VeltCollaboration />
  <DocumentCanvas />
</template>

<script setup lang="ts">
import { onMounted } from 'vue';
import { initVelt } from '@veltdev/client';
import { useVeltClient } from '@/composables/useVeltClient';
import { provideAppUser } from '@/composables/useAppUser';
import VeltInitializeUser from '@/components/velt/VeltInitializeUser.vue';
import VeltCollaboration from '@/components/velt/VeltCollaboration.vue';
import DocumentCanvas from '@/components/document/DocumentCanvas.vue';

// [Velt] Replace with your own API key from https://console.velt.dev
const VELT_API_KEY = '6xTcUFtlYAlCdh11zrKB';

const { setClient } = useVeltClient();

// Provide app user context
provideAppUser();

// [Velt] Initialize Velt client
onMounted(async () => {
  const client = await initVelt(VELT_API_KEY);
  setClient(client);
});
</script>

// apps/react/comments/dashboard/embedded-comments/privado-demo/app/page.tsx
"use client";
// [Velt] Provider + collaboration
import { VeltProvider } from "@veltdev/react";
import { useVeltAuthProvider } from "@/components/velt/VeltInitializeUser";
import { VeltCollaboration } from "@/components/velt/VeltCollaboration";
import DocumentCanvas from '@/components/document/document-canvas'

// [Velt] Replace with your own API key from https://console.velt.dev
const NEXT_PUBLIC_VELT_API_KEY = "6xTcUFtlYAlCdh11zrKB";

export default function Home() {
  // [Velt] Auth provider (reads from app/userAuth/useAppUser)
  const { authProvider } = useVeltAuthProvider();

  return (
    // [Velt] Wrap app with VeltProvider
    <VeltProvider
      apiKey={NEXT_PUBLIC_VELT_API_KEY}
      authProvider={authProvider}
    >
      <VeltCollaboration />
      <DocumentCanvas />
    </VeltProvider>
  );
}
