// apps/vue/comments/tables/ag-grid/multiple-tools/src/components/velt/VeltInitializeUser.vue
<template>
  <div style="display: none"></div>
</template>

<script setup lang="ts">
import { watch } from 'vue';
import { useVeltClient } from '@/composables/useVeltClient';
import { useAppUser } from '@/composables/useAppUser';
import { getVeltAuthToken } from '@/api/veltToken';

const { client } = useVeltClient();
const { user } = useAppUser();

// [Velt] Create auth provider object and pass it to the Velt client
watch(
  [client, user],
  ([veltClient, appUser]) => {
    if (!veltClient || !appUser) return;

    veltClient.setVeltAuthProvider({
      user: appUser,
      retryConfig: { retryCount: 3, retryDelay: 1000 },
      generateToken: async () => {
        return await getVeltAuthToken({
          userId: appUser.userId,
          organizationId: appUser.organizationId,
          email: appUser.email,
          isAdmin: false,
        });
      },
    });
  },
  { immediate: true }
);
</script>

// apps/react/text-editors/libraries/blocknote/blocknote-demo/components/velt/VeltInitializeUser.tsx
"use client";

import { useAppUser } from "@/app/userAuth/useAppUser";
import type { VeltAuthProvider } from "@veltdev/types";
import { useMemo } from "react";

// [Velt] Call your backend API to generate a JWT token for the user
async function getVeltJwtFromBackend(user: {
  userId: string;
  organizationId: string;
  email?: string;
}) {
  const resp = await fetch("/api/velt/token", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      userId: user.userId,
      organizationId: user.organizationId,
      email: user.email,
      isAdmin: false,
    }),
    cache: "no-store",
  });
  if (!resp.ok) {
    const err = await resp.json().catch(() => ({}));
    throw new Error(`Token API failed: ${err?.error || resp.statusText}`);
  }
  const { token } = await resp.json();
  if (!token) throw new Error("No token in response");
  return token as string;
}

export function useVeltAuthProvider() {
  // Get your app's current authenticated user to authenticate with Velt.
  const { user } = useAppUser();

  // [Velt] Create auth provider object to pass to VeltProvider
  const authProvider: VeltAuthProvider | undefined = useMemo(() => {
    if (!user) return undefined;
    return {
      user,
      retryConfig: { retryCount: 3, retryDelay: 1000 },
      generateToken: async () => {
        return await getVeltJwtFromBackend({
          userId: user.userId as string,
          organizationId: user.organizationId as string,
          email: user.email,
        });
      },
    };
  }, [user]);

  return { authProvider, user };
}
