// apps/react/comments/tables/tanstack/multiple-tools/components/document/ui-components/Toolbar.tsx
import React from 'react';
import {
  IconBold,
  IconItalic,
  IconUnderline,
  IconStrikethrough,
} from '@tabler/icons-react';
import { CellFormatting } from '../types';

interface ToolbarProps {
  toggleFormatting: (format: keyof CellFormatting) => void;
}

export const Toolbar: React.FC<ToolbarProps> = ({
  toggleFormatting,
}) => {
  const toolButton: React.CSSProperties = {
    backgroundColor: 'transparent',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    padding: '8px',
    flexShrink: 0,
    color: 'var(--app-text-secondary)',
  };

  return (
    <div style={{
      position: 'absolute',
      right: '8.67px',
      top: '8px',
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      gap: '16px',
      zIndex: 10,
    }}>
      {/* Text Formatting */}
      <div style={{ display: 'flex', gap: '0px' }}>
        <button style={toolButton} onClick={() => toggleFormatting('bold')}>
          <IconBold size={20} stroke={1.5} />
        </button>
        <button style={toolButton} onClick={() => toggleFormatting('italic')}>
          <IconItalic size={20} stroke={1.5} />
        </button>
        <button style={toolButton} onClick={() => toggleFormatting('underline')}>
          <IconUnderline size={20} stroke={1.5} />
        </button>
        <button style={toolButton} onClick={() => toggleFormatting('strikethrough')}>
          <IconStrikethrough size={20} stroke={1.5} />
        </button>
      </div>
    </div>
  );
};

// apps/vue/comments/tables/ag-grid/multiple-tools/src/components/document/ui-components/Toolbar.vue
<template>
  <div :style="{
    position: 'absolute',
    right: '8.67px',
    top: '8px',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '16px',
    zIndex: 10,
  }">
    <div :style="{ display: 'flex', gap: '0px' }">
      <button :style="toolButton" @click="$emit('toggleFormatting', 'bold')">
        <IconBold :size="20" stroke="1.5" :style="{ color: 'var(--app-text-secondary)' }" />
      </button>
      <button :style="toolButton" @click="$emit('toggleFormatting', 'italic')">
        <IconItalic :size="20" stroke="1.5" :style="{ color: 'var(--app-text-secondary)' }" />
      </button>
      <button :style="toolButton" @click="$emit('toggleFormatting', 'underline')">
        <IconUnderline :size="20" stroke="1.5" :style="{ color: 'var(--app-text-secondary)' }" />
      </button>
      <button :style="toolButton" @click="$emit('toggleFormatting', 'strikethrough')">
        <IconStrikethrough :size="20" stroke="1.5" :style="{ color: 'var(--app-text-secondary)' }" />
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import {
  IconBold,
  IconItalic,
  IconUnderline,
  IconStrikethrough,
} from '@tabler/icons-vue';

import type { CellFormatting } from '../types';

defineEmits<{
  toggleFormatting: [format: keyof CellFormatting];
}>();

const toolButton = {
  backgroundColor: 'transparent',
  border: 'none',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  cursor: 'pointer',
  padding: '8px',
  flexShrink: 0,
};
</script>
