// apps/react/comments/tables/tanstack/single-tool/components/header/header.tsx
"use client";

import { useVeltInitState } from "@veltdev/react";
import VeltTools from "@/components/velt/VeltTools";

export default function Header() {
  // [Velt] Check if Velt is initialized
  const veltInitialized = useVeltInitState();

  return (
    <div
      className="absolute top-0 right-0 z-50"
      style={{
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        gap: "8px",
        padding: "16px",
      }}
    >
      {veltInitialized && <VeltTools />}
    </div>
  );
}

// apps/vue/comments/tables/ag-grid/multiple-tools/src/components/header/Header.vue
<template>
  <div
    class="absolute top-0 right-0 z-50"
    :style="{
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      gap: '8px',
      padding: '16px',
    }"
  >
    <VeltTools />
  </div>
</template>

<script setup lang="ts">
import VeltTools from '@/components/velt/VeltTools.vue';
</script>
