// apps/react/comments/tables/ag-grid/single-tool/components/header/header.tsx
"use client";

import VeltTools from "@/components/velt/VeltTools";
import { ThemeToggle } from "@/components/theme/ThemeToggle";

export default function Header() {
  return (
    <div
      className="absolute top-0 right-0 z-50"
      style={{
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        gap: "8px",
        padding: "16px",
      }}
    >
      <ThemeToggle />
      <VeltTools />
    </div>
  );
}

// apps/vue/comments/tables/ag-grid/multiple-tools/src/components/header/Header.vue
<template>
  <div
    class="absolute top-0 right-0 z-50"
    :style="{
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      gap: '8px',
      padding: '16px',
    }"
  >
    <ThemeToggle />
    <VeltTools />
  </div>
</template>

<script setup lang="ts">
import VeltTools from '@/components/velt/VeltTools.vue';
import ThemeToggle from '@/components/theme/ThemeToggle.vue';
</script>
