// apps/vue/comments/tables/ag-grid/multiple-tools/src/components/velt/VeltTools.vue
<template>
  <template v-if="client">
    <!-- [Velt] Show online users -->
    <velt-presence></velt-presence>
    <!-- [Velt] Toggle comments sidebar -->
    <velt-sidebar-button></velt-sidebar-button>
    <!-- [Velt] Notifications panel -->
    <velt-notifications-tool
      settings="true"
      shadow-dom="false"
      tab-config='{"forYou":{"name":"For You","enable":true},"documents":{"name":"Documents","enable":true},"all":{"name":"All","enable":true}}'
    ></velt-notifications-tool>
  </template>
</template>

<script setup lang="ts">
import { useVeltClient } from '@/composables/useVeltClient';

const { client } = useVeltClient();
</script>

// apps/react/comments/image-editor/freestyle-comments/freestyle-comments-demo/components/velt/VeltTools.tsx
"use client";
import {
  VeltPresence,
  VeltCommentTool,
  VeltSidebarButton,
  VeltNotificationsTool,
} from "@veltdev/react";

function VeltTools() {
  return (
    <>
      {/* [Velt] Show online users */}
      <VeltPresence />
      {/* [Velt] Freestyle comments - click to pin comments anywhere */}
      <VeltCommentTool darkMode={true} />
      {/* [Velt] Toggle comments sidebar */}
      <VeltSidebarButton darkMode={true} />
      {/* [Velt] Notifications panel */}
      <VeltNotificationsTool
        settings={true}
        shadowDom={false}
        darkMode={true}
        tabConfig={{
          forYou: { name: "For You", enable: true },
          documents: { name: "Documents", enable: true },
          all: { name: "All", enable: true },
        }}
      />
    </>
  );
}

export default VeltTools;
