// apps/vue/comments/tables/ag-grid/multiple-tools/src/components/velt/ui-customization/VeltCustomization.vue
<template>
  <!-- [Velt] Wireframe customization container -->
  <velt-wireframe>
    <VeltCommentBubbleWf />
    <VeltCommentToolWf />
    <VeltNotificationsToolWf />
    <VeltSidebarButtonWf />
  </velt-wireframe>
</template>

<script setup lang="ts">
import { watch } from 'vue';
import { useVeltClient } from '@/composables/useVeltClient';
import VeltCommentBubbleWf from './VeltCommentBubbleWf.vue';
import VeltCommentToolWf from './VeltCommentToolWf.vue';
import VeltNotificationsToolWf from './VeltNotificationsToolWf.vue';
import VeltSidebarButtonWf from './VeltSidebarButtonWf.vue';
import './styles.css';

const { client } = useVeltClient();

// [Velt] Enable dark mode
watch(
  client,
  (veltClient) => {
    if (veltClient) {
      veltClient.setDarkMode(true);
    }
  },
  { immediate: true }
);
</script>

// apps/react/comments/dashboard/custom/dashboard-demo/components/velt/ui-customization/VeltCustomization.tsx
"use client";
import { useVeltClient, VeltWireframe } from "@veltdev/react";
import VeltCommentBubbleWf from "./VeltCommentBubbleWf";
import VeltCommentToolWf from "./VeltCommentToolWf";
import VeltNotificationsToolWf from "./VeltNotificationsToolWf";
import VeltSidebarButtonWf from "./VeltSidebarButtonWf";
import "./styles.css";
import { useEffect } from "react";

export function VeltCustomization() {
  // [Velt] Get Velt client instance
  const { client } = useVeltClient();

  // [Velt] Enable dark mode
  useEffect(() => {
    if (client) {
      client.setDarkMode(true);
    }
  }, [client]);

  return (
    <VeltWireframe>
      <VeltCommentBubbleWf />
      <VeltCommentToolWf />
      <VeltNotificationsToolWf />
      <VeltSidebarButtonWf />
    </VeltWireframe>
  );
}
