// apps/vue/comments/tables/ag-grid/multiple-tools/src/components/document/DocumentCanvas.vue
<template>
  <div class="flex w-full h-screen overflow-hidden" :style="{ backgroundColor: 'var(--app-bg)' }">
    <Sidebar />
    <div class="flex-1 overflow-auto relative">
      <Header />
      <DayViewTableComponent />
    </div>
  </div>
</template>

<script setup lang="ts">
import Header from '@/components/header/Header.vue';
import Sidebar from '@/components/sidebar/Sidebar.vue';
import DayViewTableComponent from './DayViewTableComponent.vue';
import { provideSidebar } from '@/composables/useSidebar';

provideSidebar();
</script>

// apps/react/comments/charts/nivo/nivo-comments-demo/components/document/document-canvas.tsx
'use client'

import { useState } from "react";
import Header from '@/components/header/header'
import Sidebar from '@/components/sidebar/sidebar'
import CommentsPanel from '@/components/comments/CommentsPanel'
import DocumentArticle from './DocumentArticle'

export default function DocumentCanvas() {
  // Host app manages the Comments drawer state
  const [commentsOpen, setCommentsOpen] = useState(false);

  const toggleComments = () => {
    setCommentsOpen((prev) => !prev);
  };

  return (
    <div className="flex w-full h-screen overflow-hidden">
      <Sidebar />
      <div className="flex-1 overflow-auto relative" style={{ backgroundColor: 'var(--app-bg)' }}>
        <Header toggleComments={toggleComments} />
        <DocumentArticle />
      </div>

      {/* Comments drawer — every data-point comment thread on the dashboard */}
      <CommentsPanel open={commentsOpen} onClose={() => setCommentsOpen(false)} />
    </div>
  )
}
